name: Flower-Power
version: 0.0.9
main: com.gabezter4.Flower_Power.Main.Main
commands:
  fp:
    description: Main Command
    usage: /fp
permissions:
  fp.leave:
    description: Leave Command
    default: not op
  fp.join:
    description: Join Command
    default: not op
  fp.spec:
    description: Spec Command
    default: not op
  fp.create:
    description: create Command
    default: op
  fp.start:
    description: Start Command
    default: op
  fp.pos:
    description: Pos Commands
    default: op
  fp.spec.set:
    description: Spec Set Command
    default: op
  fp.main:
    description: Main Command
    default: not op
  fp.ahelp:
    description: Admin Help Command
    default: op
  fp.help:
    description: Help Command
    default: not op
  fp.stop:
    description: Stop Command
    default: op
  fp.admin:
    description: All Admin Commands
    default: op
    children:
      fp.start: true
      fp.stop: true
      fp.leave: true
      fp.join: true
      fp.spec: true
      fp.create: true
      fp.pos: true
      fp.stop: true
      fp.spec.set: true
      fp.main: true
      fp.ahelp: true
      fp.help: true
  fp.player:
    description: All Player Commands
    default: not op
    children:
      fp.start: false
      fp.stop: false
      fp.leave: true
      fp.join: true
      fp.spec: true
      fp.create: false
      fp.pos: false
      fp.stop: false
      fp.spec.set: false
      fp.main: true
      fp.ahelp: false
      fp.help: true